# Database Configuration
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=bitsmith_db_pass_92834
POSTGRES_HOST=db
POSTGRES_PORT=5432

# Redis Configuration
REDIS_PASSWORD=bitsmith_redis_pass_92834
REDIS_HOST=redis
REDIS_PORT=6379

# URLs
DATABASE_URL=postgres://judge0:bitsmith_db_pass_92834@db:5432/judge0
REDIS_URL=redis://:bitsmith_redis_pass_92834@redis:6379/0